### ISSUE TITLE
Where can I download the browser?

### ISSUE THREAD

**Issue by thomaswcy** [yigitkucuk/LaL#5]
Hi,
    I'm a currently Mozilla Firefox user. I would like to try this browser for it's like Firefox, it wasn't designed for earning money, it is free and open-source software.
    But when I clicked into this repository, I didn't find the binary code anywhere. Could you please tell me where could I download it?
    PS: I think this project don't have a lot of documents, which make users hard to use it.
Thomas

**Comment by YigitKucuk** [comment]
Hi thomas,
I will attach an APK file for you in the upcoming days.
The reason where there are not any documentation is that I have been working on this project locally for a long time, and I haven't actually pushed the latest features. I will upload a detailed documentation and new features in two and a half weeks.
You can fork this repository in Android Studio and build the project to obtain an APK file for yourself too.
Thanks for your interest!
Yiğit
